// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxzkpusamrplmlijgzld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4emtwdXNhbXJwbG1saWpnemxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODg0NDUsImV4cCI6MjA2MzE2NDQ0NX0.ODYsKxhwz2lq5YWm9H0L39Vh69exFwpNT83M_58Rhwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);